package Users;

public enum Position {
    INDIVIDUAL,
    EMPLOYEE_PRODUCTION, // A
    LEADER_PRODUCTION,  // B
    DIRECTOR_PRODUCTION, // C
    ACCOUNTANT, // D
    CHIEF_ACCOUNTANT, // E
    DIRECTOR_ECONOMIC, // F
    DIRECTOR, // G
    ADMINISTRATOR, //H
    CEO, // I
    SECURITY_ADMIN // J
}
