package Users;

public enum Position {
    INDIVIDUAL,
    EMPLOYEE_PRODUCTION,
    LEADER_PRODUCTION,
    DIRECTOR_PRODUCTION,
    ACCOUNTANT,
    CHIEF_ACCOUNTANT,
    DIRECTOR_ECONOMIC,
    DIRECTOR,
    ADMINISTRATOR,
    CEO,
    SECURITY_ADMIN
}
